### ISSUE TITLE
Few questions about the tests

### ISSUE THREAD

**Issue by ali-ramadhan** [stfbnc/fathon#4]
As part of https://github.com/openjournals/joss-reviews/issues/1828 my only remaining concern is regarding the tests. Perhaps my ignorance of DFA is showing but I'm actually not sure how fathon is being tested. Take the first test for example:

```python
ts1 = np.loadtxt('./tests/ts1.txt')
ts1 = fathon.toAggregated(ts1)

def test_dfa():
    pydfa = fathon.DFA(ts1)
    n1, F1 = pydfa.computeFlucVec(10, nMax=200, revSeg=True)
    H1, H_int1 = pydfa.fitFlucVec()

    assert math.isclose(H1, 0.7982194289592676)
```

1. What is the data contained in `ts1.txt`? It looks like random numbers but maybe it's real data? Is it e.g. normally distributed?
2. What is being tested? I assume the test is computing a Hurst exponent `H1` and the test is that `H1` comes out correct?
3. Where did the magic number `0.7982194289592676` come from? Is it common to compute Hurst exponents to 16 significant figures? Why do you expect this exact value for `H1`? Does it come from some analytic expression or theory? Or is this value produced by fathon itself, in which case is this a regression test?

**Comment by stfbnc** [comment]
> What is the data contained in `ts1.txt`? It looks like random numbers but maybe it's real data? Is it e.g. normally distributed?

`ts1.txt` in particular contains co2 data after the yearly cycle has been removed. The content  description of the other files has been added in `test_fathon.py`

> What is being tested? I assume the test is computing a Hurst exponent `H1` and the test is that `H1` comes out correct?

Yes, you are right. The description of what is being tested has been added before every test in `test_fathon.py`

> Where did the magic number `0.7982194289592676` come from? Is it common to compute Hurst exponents to 16 significant figures? Why do you expect this exact value for `H1`? Does it come from some analytic expression or theory? Or is this value produced by fathon itself, in which case is this a regression test?

Sorry, it was not specified, but the tests are indeed regression tests. The magic numbers have been produced by fathon and no, it is not common to compute so many significant figures, but I have done that since I do not know the precision of the testing machines on Travis CI.
This information has been added at the beginning of `test_fathon.py`

**Comment by ali-ramadhan** [comment]
Thank you for the clarification @stfbnc! Just had a look and `test_fathon.py` is much clearer now so I'll close this issue.

**Comment by ashwinvis** [comment]
Regression tests are nice to have, but it does not confirm, neither deny that the implementation works. In the PR that I filed just now, I am trying to reproduce a third-party tutorial. Alternatively `fathon` could be tested against some published articles not associated with the developer. Thoughts?

**Comment by stfbnc** [comment]
@ashwinvis I'll search some published results with also available data.
